name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ github.token }}
        draft: true
        generate_release_notes: true
